baseURL = "https://vishvAsa.github.io/vedAH_Rk/"
languageCode = "en-us"
title = "वेदे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/vedAH_Rk/edit/content/"
  contactLink = "https://github.com/vishvAsa/vedAH_Rk/issues/new"
  fullSearchURL = "/full_search"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2


[module]

  [[module.mounts]]
    source = "../vedAH-content"
    target = "content"

  [[module.mounts]]
    source = "../vedAH-static"
    target = "static"

