name: Build Hugo site

on:
  push:
    branches: [ static ]
  pull_request:
    branches: [ static ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: 'warning'

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Basic info
      run: |
        echo "Partial variables"
        echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART }}"
        echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART }}"
        echo "Slug variables"
        echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG }}"
        echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}"
        echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
        echo "   ref                 : ${{ env.GITHUB_REF_SLUG }}"
        echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG }}"
        echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG }}"
        echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG }}"
        echo "Slug URL variables"
        echo "   repository          : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
        echo "   repository owner    : ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG_URL }}"
        echo "   repository name     : ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}"
        echo "   ref                 : ${{ env.GITHUB_REF_SLUG_URL }}"
        echo "   head ref            : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
        echo "   base ref            : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
        echo "   event ref           : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
        echo "Short SHA variables"
        echo "   sha                 : ${{ env.GITHUB_SHA_SHORT }}"
        echo "   pull request sha    : ${{ env.GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT }}"
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        submodules: false
        # Setting true above seems to lead to submodule updation problems.
        fetch-depth: 1
    - name: Get changed files
      id: changed-files
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: jitterbit/get-changed-files@v1
    - name: Update submodules
      id: update_submods
      if: ${{ steps.changed-files.conclusion == 'skipped' || (!contains(steps.changed-files.outputs.all, 'content') ) }}
      run: |
        set -o xtrace
        git submodule update --init --recursive
        git submodule update --remote --merge --recursive
    - name: Set content to pull request
      if: ${{ github.event_name == 'pull_request'}}
      uses: actions/checkout@master
      with:
        path: static
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      if: steps.update_submods.conclusion == 'success'
      id: setup_hugo
      with:
        hugo-version: "0.83.1"
        # extended: true
      # Step 3 - Clean and don't fail
    - name: Clean build_github directory
      id: clean_build
      if: steps.setup_hugo.conclusion == 'success'
      run: rm -rf build_github
    - name: Build hugo site pages
      id: hugo_build
      if: steps.clean_build.conclusion == 'success'
      run: |
        hugo
    - name: Deploy
      if: ${{ github.event_name != 'pull_request' && steps.hugo_build.conclusion == 'success'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_github
        publish_branch: gh-pages